#!/bin/sh

if [ -f /usr/bin/hmtsu ]
then
    echo "hmtsu: symbolic link to hmtsu already exists in /usr/bin/"
else
    ln -s /opt/hmtsu/bin/hmtsu /usr/bin/hmtsu
fi

if [ -f /usr/bin/hmtsudo ]
then
    echo "hmtsu: symbolic link to hmtsudo already exists in /usr/bin/"
else
    ln -s /opt/hmtsu/bin/hmtsu /usr/bin/hmtsudo
fi

if [ -f /usr/bin/hmtadn ]
then
    echo "hmtsu: symbolic link to hmtadn already exists in /usr/bin/"
else
    ln -s /opt/hmtsu/bin/hmtsu /usr/bin/hmtadn
fi
